management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
   oauth2:
     resource:
       userInfoUri: http://localhost:8901/auth/user
#       loadBalanced: true

server:
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          brokers: localhost
          #zk-nodes: localhost
